spring.application.name=ms-empresa

# Banco
spring.datasource.url=jdbc:mysql://localhost:3306/ms-empresa-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create

# Exibir SQL gerado no console
spring.jpa.show-sql=true

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/

# Identificação e health-checks
server.port=0
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Feign Client
spring.cloud.openfeign.discovery.enabled=true
logging.level.feign.client=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
