spring.application.name=gateway
server.port=8082

jwt.secret=${UNICOS-JWT-SECRET}
jwt.issuer=${UNICOS-JWT-ISSUER}

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.main.web-application-type=reactive

# Discovery Locator (se quiser acessar sem rota fixa)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*
