spring.application.name=ms-autenticacao
spring.config.import=configserver:${SPRING_CONFIG_SERVER_URL}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.autenticacao-login.ignore-exceptions[0]=org.springframework.security.authentication.BadCredentialsException
resilience4j.circuitbreaker.instances.autenticacao-login.ignore-exceptions[1]=org.springframework.security.authentication.DisabledException
resilience4j.circuitbreaker.instances.autenticacao-login.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException